# Generated by Django 6.0.2 on 2026-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subscription_plan', models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro')], default='Basic', max_length=20)),
                ('br_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created'],
            },
        ),
    ]
